version: 2.1

orbs:
  node: circleci/node@5.0.0
  snyk: snyk/snyk@1.1.2

jobs:
  run-tests:
    docker:
      - image: cimg/node:16.14.0
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command: |
            npm run test-ci
      - run:
          name: Copy tests results for storing
          command: |
            mkdir test-results/
            cp test-results.xml test-results/
          when: always
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

  security-scan:
    docker:
      - image: cimg/node:16.14.0
    steps:
      - checkout
      - node/install-packages
      - snyk/scan:
          fail-on-issues: true
          severity-threshold: high

  # Just to illustrate flow and access control. Does not actually deploy in this example.
  deploy-app:
    parameters:
      env:
        type:
          string
        default:
          dev
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "Deploy << parameters.env >>!"

  check-env-var:
    docker:
      - image: cimg/base:stable
    steps:
      - run: |
          if [[ -z "${MY_SAMPLE_VARIABLE}" ]]; then
            echo "MY_SAMPLE_VARIABLE is set - job passing"
            exit 0
          else
            echo "MY_SAMPLE_VARIABLE is not set - job will fail!"
            exit 1
          fi


workflows:
  build-test-deploy:
    jobs:
      - run-tests
      - check-env-var
      - security-scan:
          context: snyk
      - deploy-app:
          env: dev
          name: deploy-app-dev
          context: contributors
          requires:
            - run-tests
            - security-scan
            - check-env-var
          filters:
            branches:
              only: 
                - main
      - approve-for-prod:
          type: approval
          requires:
            - deploy-app-dev
      - deploy-app:
          env: prod
          name: deploy-app-prod
          requires:
            - approve-for-prod
          context: inner-team
