version: 2.1

orbs:
  node: circleci/node@5.0.0
  snyk: snyk/snyk@1.1.2

parameters:
  scheduled:
    type: boolean
    default: false

jobs:
  build-and-test:
    parameters:
      node_version:
        type: string
        default: 16.14.0
    parallelism: 4
    docker:
      - image: cimg/node:<< parameters.node_version >>
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command: |
            npm run test-ci
      - run:
          name: Copy tests results for storing
          command: |
            mkdir test-results/
            cp test-results.xml test-results/
          when: always
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

  security-scan:
    docker:
      - image: cimg/node:16.14.0
    steps:
      - checkout
      - node/install-packages
      - snyk/scan:
          fail-on-issues: true


  deploy-app:
    parameters:
      env:
        type:
          string
        default:
          dev
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "Deploy << parameters.env >>!"

workflows:
  build-test-deploy:
    jobs:
      - run-tests
      - security-scan
      - deploy-app:
          env: dev
          requires:
            - run-tests
            - security-scan
      - approve-for-prod:
          type: approval
          requires:
            - deploy-dev
      - deploy-app:
          env: prod
          requires:
            - approve-for-prod
